woowacourse-teams/2023-zipgo

backend/deploy.sh
=> 서버 배포 스크립트 작성

backend/build.gradle
> 백엔드 코드 커버리지가 90퍼가 넘어가지 않으면 빌드가 실패하도록 설정
#28 
> 
테스트 실행 후 각 클래스 별 파일을 html 파일 형태로 시각화하여 볼 수 있도록 설정
경로 -> build/jacoco/index.html/index.html
- ZipgoApplication(*Application)
- 예외 (*Exception)
- DTO( *Request, *Response )
는 커버리지 계산에서 제외하도록 설정하였습니다~!
커버리지가 기준점(현 설정값 0.9)를 넘지 못하면 테스트시 아래처럼 빌드 실패합니다
=> 백엔드 코드 커버리지 설정(with Jacoco)

backend/src/main/java/zipgo/controller/dto/GetPetFoodsResponse.java, backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> 응답 형식 수정했어요
petFoods 리스트의 프로퍼티명을 foodList로 직렬화합니다
- closes: #31
```json
{
"foodList": [
{
"id": 1,
"imageUrl": "https://avatars.githubusercontent.com/u/94087228?v=4",
"name": "[고집] 돌아온 배배",
"purchaseUrl": "https://github.com/woowacourse-teams/2023-zipgo"
},
{
"id": 2,
"imageUrl": "https://avatars.githubusercontent.com/u/76938931?v=4",
"name": "[고집] 갈비 맛 모밀",
"purchaseUrl": "https://github.com/woowacourse-teams/2023-zipgo"
}
]
}
```
테스트 했어여
=> 식품 목록 조회 API 응답 형식 수정

backend/src/main/java/zipgo/controller/GlobalExceptionHandler.java, backend/src/main/java/zipgo/controller/dto/ErrorResponse.java, backend/src/main/java/zipgo/exception/KeywordException.java, backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java, backend/src/test/java/zipgo/controller/GlobalExceptionHandlerTest.java
> 예외 응답에 형식이 생겼습니다.
- 원래는 ResponseEntity로 바디에 데이터를 바로 넣어주기로 했었는데, 논의 후 에러에 응답 형식을 추가하기로 결정했습니다.
- 그리고 Exception을 잡는 핸들러에 형식을 적용했습니다
- closes: #27 
> 유의사항..
엔드포인트가 존재하지 않을 때는 예외가 발생하지 않고 NoHandlerFoundException은 따로 설정해줘야 발생합니다
따로 설정을 해줘야합니다 설정 방법: https://tecoble.techcourse.co.kr/post/2021-11-24-spring-customize-unhandled-api/
근데 제가 .. 쇼핑 미션때 경험한 바로는 정적 파일을 관리하는 입장에서 저걸 적용하는게 좀 귀찮았어요. 글처럼 쉽게 안됐었거든요
생각을 해보면
경로가 없어서 나는 예외를 만난 클라이언트가 바디까지 열어볼 필요가 있나? 그리고 있다고 해도 원래의 응답으로도 디버깅이 가능해요.
그래서 NoHandlerFoundException의 404 응답은 처리를 해주지 않아도 될것같아 적용하지 않고 PR 생성합니다
=> 에러 응답 형식 추가

backend/src/main/resources/application-prod.yml
- closes: #15
> yml에 맞게 서버에 환경변수 설정해놨습니다.
=> prod yml 생성

backend/build.gradle
> jar 패키지에 rest docs가 포함 되지 않는 버그가 있어서 수정
src/main/resources/static/docs/ -> build/resources/main/static/docs
> 날 막을 수 있는 트러블따윈 없다 ㅋㅋ  별거 없네
=> hotfix: api 문서 복사 위치 변경

backend/src/main/java/zipgo/petfood/domain/Reviews.java, backend/src/test/java/zipgo/petfood/domain/ReviewsTest.java
> 
- closes: #172
> 
근데 한 자릿수까지 보여주는 것도 맞는건지는 모르겠어여. 그냥 자연수가 나은가여?
=> fix: 리뷰 평균을 소수점 한자리 수까지만 응답하도록 함

frontend/src/components/Review/ReviewForm/ReviewForm.tsx, frontend/src/hooks/query/review.ts
리뷰 추가할 때는 `reviewId`에 -1이 들어가는데 이 상태에서 리뷰 아이템 조회 쿼리(리뷰 수정을 위한)가 실행돼서 에러가 뜨는 문제를 해결하고자
`useReviewItemQuery`에 `enabled: payload.reviewId > 0`를 추가했습니다.
> 
- close #242
=> fix: reviewId가 0보다 클 경우에만 리뷰아이템조회 쿼리 실행하도록 수정

backend/src/main/java/zipgo/common/config/S3Config.java
> #237 
>  EC2 인스턴스 내 기본 프로필을 사용하도록 변경
=> hotfix: aws 인증정보 사용시 ec2 내부의 기본 프로필을 사용하도록 변경

backend/src/main/java/zipgo/pet/application/PetService.java, backend/src/main/java/zipgo/pet/application/dto/PetDto.java, backend/src/main/java/zipgo/pet/domain/repository/BreedsRepository.java, backend/src/main/java/zipgo/pet/presentation/PetController.java, backend/src/main/java/zipgo/pet/presentation/dto/request/CreatePetRequest.java, backend/src/main/java/zipgo/pet/presentation/dto/request/UpdatePetRequest.java, backend/src/test/java/zipgo/pet/application/PetServiceTest.java, backend/src/test/java/zipgo/pet/domain/fixture/BreedsFixture.java, backend/src/test/java/zipgo/pet/domain/fixture/PetSizeFixture.java, backend/src/test/java/zipgo/pet/domain/repository/BreedsRepositoryTest.java, backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
사용자가 등록/수정하려는 반려동물이 
1 ) 믹스견일 경우
- `견종(Breed)`과 `크기(PetSize)`를 모두 입력받는다
2 ) 믹스견이 아닐 경우
- `견종(Breed)`만 입력받는다
```java
// CreatePetRequest , UpdatePetRequest
public record CreatePetRequest (
@NotBlank(message = "Null 또는 공백이 포함될 수 없습니다. 올바른 값인지 확인해주세요.")
String name,
@NotBlank(message = "Null 또는 공백이 포함될 수 없습니다. 올바른 값인지 확인해주세요.")
String gender,
@NotNull // 사용자가 이미지를 등록하지 않을 시, 빈 문자열 등록
String imageUrl,
@Max(value = 20, message = "나이는 최대 20까지 입력 가능합니다.")
@Min(value = 0, message = "나이는 최소 0부터 입력 가능합니다.")
Integer age,
@NotBlank(message = "Null 또는 공백이 포함될 수 없습니다. 올바른 값인지 확인해주세요.")
String breed,
@Nullable // 믹스견이 아닌 경우, 입력받지 않음
String petSize,
@Max(value = 100, message = "몸무게는 최대 100까지 입력 가능합니다.")
@Min(value = 0, message = "몸무게는 최소 0부터 입력 가능합니다.")
Double weight
) {
public PetDto toDto() {
return …
```
=> feat: 반려동물 등록/수정 플로우 변경

frontend/src/components/@common/ToolTip/ToolTip.tsx, frontend/src/pages/FoodDetail/FoodDetail.tsx
> close #305 
이렇게 고쳤습니다.
추가로 라벨 바깥 눌렀을 때 꺼지게 만듬
>
=> fix: 식품 상세 페이지 기능성 라벨 깨짐 수정

frontend/src/hooks/auth.ts
> 
로그아웃할 때 로컬스토리지에 있는 정보들을 삭제해서 로그인했을 때 펫정보를 못 불러오는 문제가 있어서
일단은 로그아웃 시 로컬스토리지에 petProfile이 남아있도록 수정했습니다.
그런데 다른 브라우저로 접속하거나 로컬스토리지를 비우면 또 같은 문제가 생길테니.. 추후에 다른 방법으로 해결해야할 것 같아요!
>
=> fix: 로그아웃 시 로컬스토리지에 petProfile이 남아있도록 수정

backend/src/main/java/zipgo/common/config/WebConfig.java, backend/src/main/java/zipgo/review/presentation/ReviewController.java, backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> 내가 누른 도움이 돼요인데 누름 여부가 false로 응답되는 버그 해결
- 도움이 돼요를 누른다
- 도움이 돼요 숫자는 늘어나지만, 누름 여부는 여전히 false로 응답이 된다.
원인은 제가 리뷰 조회 API 에서 새로 만든 OptionalAuthArgumentResolver가 등록되지 않았던 것입니다.
argument resolver가 등록되지 않았으니, 요청에 jwt가 포함되어도 authDto에 해당하는 인수는 들어오지 않게 되고
```java
@GetMapping
public ResponseEntity<GetReviewsResponse> getAllReviews(
@OptionalAuth AuthDto authDto, // null
@ModelAttribute @Valid GetReviewsRequest request) {
GetReviewsResponse reviews = reviewQueryService.getReviews(request.toQueryRequest(authDto.id()));
return ResponseEntity.ok(reviews);
}
```
따라서, 회원임에도 불구하고 항상 비회원의 요청인 것 처럼 누름 여부가 항상 false로 계산되었던 것입니다 :D
> 무민이 제보해주셨습니다 :D 감사합니다.
=> fix: optional auth argument resolver 추가

frontend/src/apis/auth.ts, frontend/src/apis/index.ts, frontend/src/components/@common/AxiosInterceptors/AxiosInterceptors.tsx, frontend/src/components/Review/ReviewItem/ReviewItem.tsx, frontend/src/components/Review/ReviewList/ReviewList.tsx, frontend/src/context/petProfile/PetProfileContext.tsx, frontend/src/hooks/auth.ts, frontend/src/hooks/query/auth.ts, frontend/src/pages/PetProfile/PetProfileEdition/PetProfileEditionContent.tsx, frontend/src/pages/PetProfile/PetProfileImageAdditionContent.tsx, frontend/src/types/auth/client.ts, frontend/src/types/auth/remote.ts, frontend/src/types/petProfile/client.ts, frontend/src/utils/localStorage.ts
- 기존 유저 정보 확인 api가 사용 가능해짐에 따라 계획했던 "토큰으로 로그인 여부 확인하기"의 변경을 보류했습니다!
- token 관련 localStorage key를 `auth` > `tokens`로 변경했습니다! ( 추후 `refreshToken` 추가를 염두하여 객체로 구현했습니다)
```tsx
interface Tokens {
accessToken: string
}
```
```tsx
const STORAGE_KEY = {
tokens: 'tokens',
userInfo: 'userInfo',
petProfile: 'petProfile',
} as const;
const getTokens = localStorageKit<Tokens>(STORAGE_KEY.tokens).getItem;
const setTokens = localStorageKit<Tokens>(STORAGE_KEY.tokens).setItem;
const tokens = getTokens() // Tokens || null
const { accessToken } = getTokens({ required: true }) // Tokens
const setTokens({ accessToken })
```
defaultValue : `unkown` | default : `null`
required : `boolean` | default : `false`
```tsx
const userInfo = zipgoLocalStorage.getUserInfo() // UserInfo || null
const { name } = …
```
=> feat: 로그인 여부 확인 로직 수정, zipgoLocalStorage 추가

frontend/src/components/PetProfile/PetProfileEditionForm/PetProfileEditionForm.stories.tsx, frontend/src/components/Review/ReviewForm/ReviewForm.stories.tsx, frontend/src/components/Review/ReviewForm/ReviewForm.tsx, frontend/src/components/Review/ReviewItem/ReveiwItem.stories.tsx, frontend/src/components/Review/ReviewItem/ReviewItem.tsx, frontend/src/constants/review.ts, frontend/src/hooks/petProfile/usePetProfileEdition.ts, frontend/src/hooks/review/useReviewForm.ts
[5차 데모데이까지 진행할 테스트 목표](https://github.com/woowacourse-teams/2023-zipgo/wiki/%5BFE%5D-%ED%85%8C%EC%8A%A4%ED%8C%85-%EC%A0%84%EB%9E%B5-%EC%88%98%EB%A6%BD-%EB%B0%8F-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%9E%90%EB%8F%99%ED%99%94)에 따라 테스트 코드를 추가했습니당
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/350c369d-8c3c-478a-9cb2-8274d3c3cb82
> 
리뷰 글자수 제한 500자로 했다가 백엔드쪽에서 막혀서 255자로 줄였습니다.
이거 어떤가요 넘 작을까요?
- close #385
=> feat: 폼 컴포넌트 테스트 추가 및 리뷰 관련 코드 리팩터링

.github/workflows/frontend-deploy-dev.yml, .github/workflows/frontend-deploy-prod.yml, frontend/.env.development, frontend/config/paths.js, frontend/config/webpack.dev.js, frontend/package.json
> 앗 근데 개발할 땐 local.env 카카오 리다이렉트 설정해둬야할듯..!
> close #387
=> chore: 프론트엔드 배포 워크플로우 dev/prod 분리

frontend/src/apis/index.ts
> 
```tsx
import axios from 'axios';
import { Tokens } from '@/types/auth/client';
import { zipgoLocalStorage } from '@/utils/localStorage';
export const { BASE_URL } = process.env;
const tokens = zipgoLocalStorage.getTokens();
const defaultConfig = {
baseURL: BASE_URL,
};
export const createConfigWithAuth = (tokens: Tokens | null) =>
tokens
? Object.assign(defaultConfig, {
headers: {
Authorization: `Bearer ${tokens.accessToken}`,
},
})
: defaultConfig;
export const clientBasic = axios.create(defaultConfig);
export const client = axios.create(createConfigWithAuth(tokens));
```
Object.assign으로 defaultConfig를 바꿔버려서 문제가 된 것!!
```tsx
export const createConfigWithAuth = (tokens: Tokens | null) =>
tokens
? {
...defaultConfig,
headers: {
Authorization: `Bearer ${tokens.accessToken}`,
},
}
: …
```
=> fix: 로그아웃이 제대로 안되는 문제 해결

frontend/package.json, frontend/src/index.tsx
> 
https://dev.zipgo.pet/(개발모드)에서는 <React.StrictMode>가 활성화되는데..
카카오 인증 요청 시 똑같은 토큰으로 2번(뒤에꺼는 폐기된 상태) 요청해서 아래와 같은 에러가 뜸
```tsx
// package.json
{
...
"scripts": {
"start:dev": "cross-env NODE_ENV=development MSW=on STRICT_MODE=on webpack serve --config config/webpack.dev.js",
"build:dev": "cross-env NODE_ENV=development webpack STRICT_MODE=off --progress --config config/webpack.dev.js",
...
},
...
}
```
```tsx
// index.tsx
...
const strictMode = process.env.STRICT_MODE === 'on';
const app = (
<QueryClientProvider client={queryClient}>
<QueryBoundary errorFallback={errorFallback}>
<Router />
</QueryBoundary>
</QueryClientProvider>
);
root.render(strictMode ? <React.StrictMode>{app}</React.StrictMode> : app);
```
> 
- close #394
=> fix: dev.zipgo.pet 로그인 시 에러나는 문제 해결

frontend/Dockerfile, frontend/Dockerfile.dev, frontend/src/components/PetProfile/PetItem.tsx, frontend/src/components/PetProfile/PetList.tsx, frontend/src/components/PetProfile/PetListBottomSheet.tsx, frontend/src/hooks/common/useImageUpload.ts, frontend/src/hooks/query/auth.ts, frontend/src/hooks/query/petProfile.ts, frontend/src/hooks/query/review.ts, frontend/src/hooks/review/useReviewForm.ts, frontend/src/types/review/remote.ts
> 
반려동물 여러마리 등록 기능 추가 + 기타 작은 작업들을 진행했어요~
1시간/2시간
> 
- close #396
=> feat: 반려동물 여러마리 등록 기능 추가

.github/workflows/frontend-deploy-dev.yml, .github/workflows/frontend-deploy-prod.yml, .github/workflows/storybook.yml
>  node-version: '16.x' > '18.x'
> 
- close #402
=> fix: 프론트엔드 배포 워크플로우 노드버전 18로 변경

frontend/src/hooks/query/petProfile.ts
> 
반려동물 2마리 이상일 때 1마리 삭제 시
로컬스토리지 유저 정보의 hasPet이 false가 돼서 리뷰 작성이 안되는 문제 해결했습니다!
추후에
https://github.com/woowacourse-teams/2023-zipgo/pull/398#discussion_r1325503695 > 요거 반영하면서 얘도 리팩터링 같이 할 것 같아용
> 
- close #409
=> fix: 반려동물 2마리 이상일 때 1마리 삭제 시 hasPet이 false가 돼서 리뷰 작성이 안되는 문제 해결

backend/src/main/java/zipgo/image/ImageDirectoryUrl.java
> 
접두사로 prod가 붙어있어서, 개발환경에 들어가야할 이미지들이 모두 prod 내에 들어가있습니다
이에 제거하였습니다
>
=> hotfix: s3 디렉토리 이름 접두사 제거

backend/build.gradle, backend/src/main/java/zipgo/common/config/S3Config.java, backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java, backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java, backend/src/main/java/zipgo/petfood/dto/response/GetPetFoodQueryResponse.java, backend/src/main/java/zipgo/petfood/dto/response/GetPetFoodsResponse.java, backend/src/main/java/zipgo/petfood/dto/response/PetFoodResponse.java, backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryImpl.java, backend/src/main/java/zipgo/review/application/ReviewQueryService.java, backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepository.java, backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java, backend/src/main/java/zipgo/review/presentation/ReviewController.java, backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java, backend/src/test/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryTest.java, backend/src/test/java/zipgo/petfood/presentation/PetFoodControllerTest.java, backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java, backend/src/test/java/zipgo/review/application/ReviewsServiceTest.java, backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
- #423 
현재 가장 유의미해보이는 api 3개 쿼리 개선해보았습니다. 내일 ngrinder로 성능 테스트 할 예정입니다.
1. 펫푸드 조회 쿼리
- 불필요한 필드 제거 후 dto 반환
- 중복 제거 distinct -> group by
- 데이터 100만 건 기준으로 distinct로 조회했을 떄 1분 걸렸는데 group by로 조회시 100ms만에 조회, 왜 그런지는 좀 더 알아볼 예정
2. 개별 리뷰 조회 
- 원래 6개에서 2개로 (before: 70 ~ 110ms, after 10 ~ 30ms)
4. 개별 식품 조회
- 원래 6개에서 4개로
대부분의 쿼리는 한방 쿼리 또는 인덱스를 알아서 잘타고 있엇기 때문에 딱히 인덱스를 걸 일은 없었네요..
한방 쿼리로 하다 보니 한방 쿼리가 무조건 좋은가(또는 성능이 유의미하게 늘어나는가) 라는 의문이 들더군요.. 이 부분 좀더 공부해서 공유드리겠습니다.
그리고 아직 정확하게 성능 측정을 한게 아니다보니 아직 애매하네요. 내일 ngrinder로 좀 더 정확히 해보겠습니다~
>
=> refactor: 조회 쿼리 개선

frontend/Dockerfile.dev
> 
> sharp라이브러리가 현재 아키텍처에 맞게 설치되도록 도커파일에 아래와 같은 명령어를 추가해주려고 해여
> 예상되는 문제 원인은 GitHub Actions와 Docker 컨테이너 간에 호환되지 않는 아키텍처 라이브러리를 설치했기 때문인 것 같습니다.
> GitHub Actions는 주로 x86_64 (amd64) 아키텍처, Docker 컨테이너는 arm64 아키텍처로 빌드되는 경우가 많대요
`RUN yarn add sharp --platform=linux --arch=arm64`에서 --platform 및 --arch 옵션은 yarn 명령어에는 사용되지 않는 옵션이라구해서 다시 수정합니다..
```tsx
RUN yarn add sharp
```
```tsx
// Dockerfile.dev
FROM --platform=linux/arm64 node:18.16.1-alpine as builder
WORKDIR /app
COPY . /app
RUN yarn add sharp # 추가!!
RUN yarn build:dev
FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
```
=> fix: 도커파일 잘못된 명령어 수정

backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java, backend/src/main/java/zipgo/petfood/dto/request/PetFoodSelectRequest.java, backend/src/main/java/zipgo/review/dto/response/type/RatingInfoResponse.java, backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java, backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
=> feat: 리뷰 요약 조회 json 프로퍼티 명 수정

backend/src/main/java/zipgo/aspect/ConnectionProxyHandler.java, backend/src/main/java/zipgo/aspect/QueryCounter.java, backend/src/main/java/zipgo/aspect/QueryCounterAop.java, backend/src/main/java/zipgo/common/config/WebConfig.java, backend/src/main/java/zipgo/common/interceptor/LoggingInterceptor.java, backend/src/test/java/zipgo/admin/presentation/AdminControllerMockTest.java, backend/src/test/java/zipgo/auth/presentation/AuthControllerTest.java, backend/src/test/java/zipgo/common/acceptance/MockMvcTest.java, backend/src/test/java/zipgo/image/presentaion/ImageControllerTest.java
- close: #444 
상세한 내용은 issue 혹은 [블로그](https://parkmuhyeun.github.io/woowacourse/2023-09-23-query-counter/) 참고하시면 될 것 같고 결과는 다음과 같습니다!
>
=> feat: 쿼리 카운터 적용

.github/workflows/frontend-storybook-deploy.yml
> 
EC2 aws cli를 사용하여 스토리북을 S3로 배포하려고합니다!
현재 이미지 저장용 s3가 1개 있어서 요걸 사용하려고 해요.
그래서 아마 배포 후 접근은 `image.zipgo.pet/storybook/index.html` 경로로 들어가야 할 것 같습니디. 
아니면 CloudFront배포 주소+`/storybook/index.html`로도 접근할 수 있을 것 같아요.
깃허브액션에서 도커 컨테이너 생성 시 스토리북 빌드 부분에서 문제가 있었음
1. 깃허브액션에서의 아키텍처 환경과 도커 컨테이너 내부 환경이 달라서 패키지 설치가 제대로 설치되지 않는 것 같아서(추측) 도커 베이스이미지를 node:18.16.1-alpine에서 두 환경 모두 지원하는 node로 바꿔보았으나 안됨
2. 깃허브액션에서 바로 s3로 빌드 파일을 업로드하려 했으나 해당 작업은 aws key가 필요한데 보안상의 이유로 받을 수 없음..
깃허브액션에서 ec2 서버(s3에 접근할 수 있는 IAM권한을 가지고있음)를 self-hosted runner로 등록해서 aws cli를 사용해 ec2 > s3로 빌드파일 업로드하는 방식으로 워크플로우를 작성했습니다.
다른 레포에서 한번 시도 해봤는데 잘 되더라고여 우리 프로젝트에서도 잘 되겠죠..?
> 
- close #462
=> chore: 스토리북 S3 배포 워크플로우 추가

.github/workflows/frontend-storybook-deploy.yml, frontend/.storybook/preview.tsx
> 
- 클라우드 프론트 권한이 없어서 캐시 무효화 로직을 수행하지 못함 > 그래서 해당 로직을 삭제했습니다.
- 스토리북에서 mockServiceWorker를 https://d18wpz6q8kn3i7.cloudfront.net/mockServiceWorker.js에서 찾는 문제가 있는데 로컬호스트네임에 따라서 경로를 바꿔주는 로직을 추가해서 d18wpz6q8kn3i7.cloudfront.net/storybook/mockServiceWorker.js에서 찾도록 설정했습니다.
```tsx
// preview.tsx
let options = {};
if (location.hostname.includes('cloudfront')) {
options = {
serviceWorker: {
url: '/storybook/mockServiceWorker.js',
},
};
}
// Initialize MSW
initialize(options);
```
> 
- close #465
=> fix: 스토리북 배포 워크플로우에서 캐시 무효화 로직 삭제 및 mockServiceWorker 경로 수정

.github/workflows/frontend-storybook-deploy.yml
> 
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
위와 같은 경고가 떠서 캐시 경로를 수정했습니다!
```yaml
- name: Cache Yarn global cache
uses: actions/cache@v3
with:
path: '**/.yarn'
key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
restore-keys: |
${{ runner.os }}-yarn-
- name: Cache Yarn project cache
uses: actions/cache@v3
with:
path: '**/.yarn/cache'
key: ${{ runner.os }}-yarn-project-${{ hashFiles('**/yarn.lock') }}
restore-keys: |
${{ runner.os }}-yarn-project-
```
> 
- close #467
=> fix: 스토리북 배포 워크플로우 캐시 경로 수정

frontend/src/components/FoodSelectionGuideBanner/FoodSelectionGuideBanner.tsx, frontend/src/components/PetProfile/PetProfileEditionForm/PetProfileEditionForm.stories.tsx, frontend/src/components/Review/ReviewForm/ReviewForm.stories.tsx, frontend/src/hooks/food/useFoodSelectionGuideBanner.ts
'사료 선택 도움말 배너' 닫기 버튼 클릭 후에는 리액트 내부 페이지 이동 시 안 보이도록 수정했어요.
광고 배너가 아니라 우리 서비스에서 고민한 부분이 잘 전달 되도록 하기 위해 추가한 아이이기 때문에
새로고침 시에도 안 보이게 하는 것보단 우리 서비스 내부 페이지 이동 시에만 '닫힘' 상태를 유지하는 것이 좋다고 판단했습니다.
- 추가작업) 빠른 테스트를 위해 인터랙션 테스트의 delay를 제거했습니다.
- close #483
=> refactor: '사료 선택 도움말 배너'를 닫으면 리액트 내부 페이지 이동 시 안 보이도록 수정

frontend/src/components/@common/Input/Input.tsx, frontend/src/components/@common/Label/Label.tsx, frontend/src/components/Food/FilterBottomSheet/MainIngredientsFilterList/MainIngredientsFilterList.tsx, frontend/src/components/PetProfile/PetAgeSelect.tsx, frontend/src/components/PetProfile/PetBreedSelect.tsx, frontend/src/components/PetProfile/PetProfileEditionForm/PetProfileEditionForm.tsx, frontend/src/components/Review/ReviewForm/ReviewForm.tsx, frontend/src/components/Review/ReviewListAndChart/ReviewControls/AlignSelect/AlignSelect.tsx, frontend/src/components/Review/ReviewListAndChart/ReviewControls/FilterDialog/FilterDialog.tsx, frontend/src/pages/PetProfile/PetProfileAddition/PetProfileNameAddition.tsx, frontend/src/pages/PetProfile/PetProfileAddition/PetProfileWeightAddition.tsx, frontend/src/styles/globalStyle.ts
모바일 디바이스에서 `<input>`, `<textarea>` 포커스 시 자동 zoom-in되는 현상을 개선했습니다.
`font-size`가 `16px`보다 작으면 자동으로 zoom-in된다고 해요. 
이를 개선하기 위한 3가지 방법이 있습니다.
1. input, textarea에서는 `font-size`를 `16px`이상으로 바꾸기
2. `<meta>`를 이용해 확대 자체를 막기 
`<meta
name="viewport"
content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
/>`
3. 폰트 크기는 16px로 적용하고 `transform: scale()`을 이용해서 원하는 폰트 크기로 조절하기
고민을 해봤는데.. 1번 방법을 적용했어요.
아무래도 사용자가 편하게 쓸 수 있어야 하니까요!
W3C/WAI 모바일 접근성 가이드[(Zoom/Magnification)](https://www.w3.org/TR/mobile-accessibility-mapping/#zoom-magnification)에서도 메타 요소의 사용자 확장 가능 속성 및 최대 규모 속성에 대해 제한하는 건 피하는 게 좋다고 합니다.
> Ensure that the browser pinch zoom is not blocked by the page's viewport meta element so that it can be used to zoom the page to 200%. Restrictive values for user-scalable and …
=> feat: 모바일 디바이스(ios)에서 <input>, <textarea> 포커스 시 자동 zoom-in되는 현상 개선

backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java, backend/src/main/java/zipgo/common/config/WebConfig.java
> 
로컬에서 클라이언트와 서버의 origin이 달라 쿠키가 안박히는 것으로 추정, samesite=None 옵션을 설정한다
>
=> feat: 쿠키 내 samesite=None 옵션 추가

backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> 
.zipgo.pet의 서브도메인 모두 허용하도록 도메인 추가
>
=> fix: 쿠키 내 domain 설정 추가

frontend/src/components/Review/ReviewItem/ReviewItem.tsx, frontend/src/components/Review/ReviewListAndChart/ReviewList/ReviewList.tsx, frontend/src/pages/FoodDetail/FoodDetail.tsx
> 
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/5a65c612-fe1b-4f55-9fa4-6c19f34d2acf
- 리뷰 보기 나이가 1살 미만이면, 0살 -> 1살 미만으로 떠야함
- 리뷰목록, 아래 겹쳐서 더보기 버튼 클릭할 수가 없음 -> 리뷰목록 margin 조절하기
> 
- close #511
=> fix: 0살이면 1살 미만으로 뜨도록 수정, 리뷰 더보기 클릭이 안되는 문제 해결

frontend/src/pages/Landing/Landing.tsx
> 
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/b27b8c64-0ffe-4c6d-9251-fd8e34b613e6
강아지 깨우기 이스터에그 추가했어요
제가 여러번 테스트해본 결과 150번은 너무 힘듭니다. 그래서 100번으로 줄였어요.
> 
- close #517
=> feat: 강아지 깨우기 이스터에그 추가

frontend/src/hooks/query/review.ts
> 
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/84d59140-add2-43a6-a568-0b990092fb7b
리뷰 요약 쿼리키에 `petFoodId`를 추가해줘서 모든 상품에 같은(캐싱된) 리뷰요약 정보가 보이는 문제를 해결했어요
> 
- close #519
=> fix: 리뷰요약 동기화 안되는 문제 해결

frontend/src/components/PetProfile/PetListBottomSheet.tsx, frontend/src/constants/time.ts, frontend/src/hooks/petProfile/usePetProfileEdition.ts, frontend/src/hooks/query/food.ts, frontend/src/hooks/query/petProfile.ts, frontend/src/hooks/query/review.ts
- 리뷰 서머리 차트가 캐싱되어 다른 차트가 최신화 되지 않는 현상 수정
> - close #523
=> hotfix: 리뷰 서머리 차트 캐싱 오류 수정

frontend/src/components/@common/LazyImage/LazyImage.tsx, frontend/src/components/@common/LazyImg/LazyImg.tsx, frontend/src/components/@common/SuspendedImg/SuspendedImg.tsx, frontend/src/components/Food/FoodItem/FoodItem.tsx, frontend/src/hooks/@common/useIntersectionObserver.ts
=> refactor: 식품 이미지 미처 적용 안됐던 lazy loading 적용

backend/build.gradle, backend/src/main/java/zipgo/admin/application/AdminService.java, backend/src/main/java/zipgo/admin/dto/BreedCreateRequest.java, backend/src/main/java/zipgo/admin/presentation/AdminController.java, backend/src/main/java/zipgo/common/cache/CacheType.java, backend/src/main/java/zipgo/common/config/CacheConfig.java, backend/src/main/java/zipgo/pet/application/PetQueryService.java, backend/src/main/java/zipgo/pet/domain/repository/BreedRepository.java, backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> #532 로컬 캐시 적용
1. breedRepository.findAll()에 로컬 캐싱 적용함
2. admin에 견종 등록 API 추가함
3.  (2) 번 통해 견종 추가되면 캐시 깨짐
견종 목록 같은 경우 추가될 일이 극히 드물겠죠
리뷰 조회나 식품 조회같이 필터링이 필요한 경우도 아니구요
그래서, 로컬 **캐싱을 적용해보았습니다**
[스프링 공식문서](https://docs.spring.io/spring-framework/reference/integration/cache.html) 를 보면, CacheManager라는 인터페이스를 제공합니다.  이 친구를 통해 WAS 레벨에서의 캐싱을 적용할 수 있어요!
구현체인 라이브러리는 caffeine이라는 친구를 사용했습니다
크게 구관인 [Enacache](https://github.com/ehcache/ehcache3)와 요즘 대세 [Caffeine](https://github.com/ben-manes/caffeine) 이 두 친구가 있는데, Enacahe는 xml 방식으로 사용해야하고, 스타수도 10배씩이나 차이나서 caffeine으로 선택했습니다
[CacheConfig](https://github.com/woowacourse-teams/2023-zipgo/blob/feat/%23532/backend/src/main/java/zipgo/common/config/CacheConfig.java) 설정을 통해, CacheManager와  Caffeine을 Bean으로 등록했어요
`@CacheEvict(cacheNames = "breeds", key = …
=> feat: 견종 목록 조회시 로컬 캐시 적용

frontend/src/components/PetProfile/PetInfoInForm.tsx, frontend/src/components/PetProfile/PetProfileEditionForm/PetProfileEditionForm.tsx, frontend/src/components/PetProfile/PetProfileImageUploader.tsx, frontend/src/constants/petProfile.ts, frontend/src/hooks/@common/useImageUpload.ts, frontend/src/hooks/petProfile/usePetProfileEdition.ts, frontend/src/pages/PetProfile/PetProfileAddition/PetProfileImageAddition.tsx
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/2b8d6bda-5247-49b9-80c0-e88df5310c0e
반려동물 프로필 이미지를 추가하거나 수정할 때 아래와 같은 단계를 거칩니다.
- 이미지 파일 압축 > 압축된 이미지 파일 서버에 업로드 > 서버로부터 이미지 URL을 응답받음
네트워크 상태를 slow 3g로 설정한 후 테스트해보니, 이미지가 업로드 되기 전에 등록 버튼을 누르면 프로필 이미지가 제대로 등록되지 않더라구요!
- 압축 중인 경우 > 압축 진행률을 보여줍니다.
- 업로드 중인 경우 > 로딩 스피너를 보여줍니다.
- 이미지 압축 중이거나 업로드 중인 경우 > 버튼을 비활성화합니다.
- 반려동물 이미지 최대 가로, 세로 너비를 `200 -> 1000px`로 수정(압축 라이브러리 설정 중 `maxWidthOrHeight` 값 변경)
- 문제: 만약 `1:9` 비율의 이미지라고 하면 가로 약`22px`, 세로 `200px`이 되는데 이 이미지를 프로필 사이즈(`55x55`)로 늘리게 되면 이미지가 심하게 깨짐
- 해결: `110px`(55x2)을 기준으로 하면 `990px`을 최대 너비로 설정하면 됨 -> 조금 더 넉넉하게 `1000px`로 설정
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/f564503d-3282-4504-a12c-9e6b9d1a11b5 …
=> fix: 반려동물 프로필 이미지 추가, 수정 시 이미지 업로드 도중 폼 제출 못하도록 수정
