woowacourse-teams/2023-zipgo

- frontend/.eslintrc.js
- frontend/.storybook/preview.tsx
- frontend/src/App.tsx
- frontend/src/styles/styled-components.d.ts
- frontend/src/styles/theme.ts
> Styled-Components ThemeProvider 적용

- frontend/.env.development
- frontend/src/apis/food.ts
- frontend/src/apis/index.ts
- frontend/src/components/@common/ErrorBoundary.tsx
- frontend/src/components/@common/QueryBoundary.tsx
- frontend/src/hooks/query/food.ts
- frontend/src/index.tsx
- frontend/src/mocks/fixtures/food.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/handlers/food.ts
- frontend/src/mocks/handlers/index.ts
- frontend/src/mocks/worker.ts
- frontend/src/types/common/errorBoundary.ts
- frontend/src/types/common/utility.ts
- frontend/src/types/food/client.ts
- frontend/src/types/food/remote.ts
```jsx
const Component = () => {
const { foodList } = useFoodListQuery({ keyword: [] });
...
return (
...
)
}
```
```jsx
const Component = () => {
const loadingFallback = <div>loading...</div>;
const errorFallback = ({ reset }: ErrorBoundaryValue) => (
<button type="button" onClick={reset}>
retry
</button>
);
...
return (
<QueryBoundary loadingFallback={loadingFallback} errorFallback={errorFallback}>
<Child />
</QueryBoundary>
)
}
```
> - close #13
> 식품 목록 조회 API 인터페이스 구현

- frontend/.eslintrc.js
- frontend/.stylelintrc.js
- frontend/src/components/@common/Checkbox/Checkbox.stories.tsx
- frontend/src/components/@common/Checkbox/Checkbox.tsx
- frontend/src/components/FilterSwitch/FilterSwitch.stories.tsx
- frontend/src/components/FilterSwitch/FilterSwitch.tsx
- frontend/src/styles/theme.ts
```tsx
interface FilterSwitchProps extends ComponentPropsWithoutRef<'input'> {
isActive: boolean;
setIsActive: Dispatch<SetStateAction<boolean>>;
labelText?: string;
backgroundColor?: string;
filterSize?: 'small' | 'medium' | 'large';
css?: CSSProp;
}
```
필터 on/off 시 `isActive`를 `true/false`로 변경합니다.
> `yarn start:sb`로 실행하면 됩니당
> lint 설정도 조금 변경했습니당 스토리북에서 린트에러나서...
> 식품 목록 다이어트 필터 컴포넌트 구현

- frontend/.dockerignore
- frontend/.yarnrc.yml
- frontend/Dockerfile
- frontend/conf/conf.d/default.conf
- frontend/config/webpack.common.js
> close #8 
>  추가적으로 yarn nodeLinker pnp 설정해줬습니다
> 프론트엔드 CI/CD 구축

- .github/CODEOWNERS
> #54 CODEOWNER를 설정했습니다
backend/ 폴더의 내용이 변경되면 백엔드 크루가 리뷰어로 등록을
frontend/ 폴더의 내용이 변경되면 프론트 크루가 리뷰어로 등록을
.github/은 다 리뷰어로 등록되도록 설정
복붙해온거긴한데 혹시모르니 자기 아이디 오타 없나 확인 부탁드립니다 ~
> CODEOWNER 설정을 통한 Auto Assign 추가

- frontend/.eslintrc.js
- frontend/src/apis/food.ts
> fix: getFoodList keyword undefined 제대로 리턴되도록 수정

- .github/workflows/gradle.yml
> feat: 백엔드 CI

- backend/lombok.config
- backend/src/main/java/zipgo/petfood/domain/Keyword.java
- backend/src/main/java/zipgo/petfood/domain/PetFood.java
- backend/src/test/java/zipgo/petfood/domain/KeywordTest.java
- backend/src/test/java/zipgo/petfood/domain/fixture/PetFoodFixture.java
- backend/src/test/java/zipgo/petfood/domain/repository/PetFoodRepositoryTest.java
- backend/src/test/java/zipgo/petfood/service/PetFoodServiceTest.java
> PetFood랑 Keyword에 빌더 추가했어요
음.. 추가로 jacoco가 롬복은 커버리지 대상에서 제외하게 하는 거 했는데 이거 PR 따로 써야할까요?
> ㅎ
참고: [스택오버플로 - jacoco에서 generated code 제외하는 법이 뭐죠?](https://stackoverflow.com/questions/29520912/jacoco-exclude-generated-methods-using-it-with-lombok)
> refactor: 기존 도메인 객체에 builder 추가

- backend/src/main/java/zipgo/brand/domain/Brand.java
- backend/src/main/java/zipgo/petfood/domain/PetFood.java
- backend/src/test/java/zipgo/brand/domain/BrandTest.java
- backend/src/test/java/zipgo/petfood/domain/PetFoodTest.java
> feat: Brand 엔티티 생성

- backend/build.gradle
- backend/src/main/java/zipgo/ZipgoApplication.java
- backend/src/main/java/zipgo/common/entity/BaseTimeEntity.java
- backend/src/main/java/zipgo/member/domain/Member.java
- backend/src/main/java/zipgo/review/domain/AdverseReaction.java
- backend/src/main/java/zipgo/review/domain/Review.java
- backend/src/main/java/zipgo/review/domain/StoolCondition.java
- backend/src/main/java/zipgo/review/domain/TastePreference.java
- backend/src/main/java/zipgo/review/repository/ReviewRepository.java
> 식품 상세 기능 구현에서 식품에 따른 리뷰 조회 기능이 필요해 우선적으로 구현해 pr #66
+일단 필요한 최소한의 부분만 구현했고 추가적으로 구현할 예정
>
> feat: 리뷰 조회 기능 부분 

- backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodsResponse.java
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> refactor: GetPetFoodsResponse 프로퍼티명 수정

- backend/src/main/java/zipgo/auth/exception/AuthException.java
- backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
- backend/src/main/java/zipgo/review/application/ReviewService.java
- backend/src/main/java/zipgo/review/domain/Review.java
- backend/src/main/java/zipgo/review/domain/repository/ReviewRepository.java
- backend/src/main/java/zipgo/review/dto/request/UpdateReviewRequest.java
- backend/src/main/java/zipgo/review/exception/ReviewException.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
- backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
- backend/src/test/resources/data.sql
-  close: #64 
> 얏호! 이제 하나 남았다~
불편했던 점
- exception에 상태코드가 없으니깐 exception 늘어날 때마다 하나하나 추가해줘야 됨
-> 관리 포인트가 늘어난다는 단점 체감
- pr 날리는 단위를 엄청 잘게 쪼개는 것도 좋지 않겠다.
- 사이클 빨리 빨리 안 도는거 같아 -> 생산성이 많이 느려지는듯
> feat: 리뷰 수정 기능 구현

- frontend/src/components/@common/Checkbox/Checkbox.tsx
- frontend/src/utils/compound.ts
> refactor: Checkbox 로직 수정

- backend/src/main/java/zipgo/review/application/ReviewService.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
- close: #65 
> 얏호 마지막 Pr~ 하지만 리팩토링하고 해야겠g..
> feat: 리뷰 삭제 기능 구현

- backend/build.gradle
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> fix: 스웨거 서버 추가

- backend/src/main/java/zipgo/auth/util/JwtProvider.java
- backend/src/main/java/zipgo/common/config/JwtCredentials.java
- backend/src/test/resources/application.yml
> #60 
> expire-length-milli-second -> expire-length
> hotfix: JwtCredential 필드명 수정

- backend/src/main/resources/application-prod.yml
> hotfix: osiv를 true로 변경

- backend/src/main/java/zipgo/common/config/WebConfig.java
> hotfix: 개발 앱 origin 추가

- backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
> #60 소셜 로그인 구현
컨플릭트 잡다가 놓친 것 같네요
앞으로 작업 단위를 작게 가져가야 한다는 교훈과..
컨플릭트는 신중히 잡아야 한다는 교훈을...
> hotfix: AuthException 예외처리

- backend/deploy.sh
- backend/src/main/resources/application-dev.yml
> support: 배포스크립트 Profiles 변경

- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> close: #117 
리뷰 개별 조회 기능이요~
> ㄴ
> feat: 리뷰 개별 조회 기능 구현

- backend/deploy.sh
> hotfix: 스크립트 pid 변수명

- backend/src/main/java/zipgo/common/config/WebConfig.java
> refactor: CORS origin 변경

- backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
- backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
- backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceUnitTest.java
- backend/src/test/java/zipgo/petfood/domain/fixture/PetFoodFixture.java
- backend/src/test/resources/data.sql
> #124 
코드를 최대한 깔끔하게 짜보려고 했으나... 로우에 ,(콜론)이 있어서 만족스럽게 만들진 못한것같습니다.(Querydsl 한방쿼리로 구현하려다가 안되서 jpql로도 해봤는데 안되서 빡구현했습니다. 코드 더러워도 이해좀... 나중에 제가 꼭 책임지고 리팩터링 할게용) 그리고 최대한 API 명세도 맞추고 예외도 없으면 좋겠어서 테스트 케이스도 여러가지 상황에 맞게 짜봤습니다. 아 단위 테스트는 아직 못했는데 내일 아침에 가서 추가해놀게요~~
추가로 이번에 한 작업 요약입니다! 저게 저렇게만 보면 귀여워 보이는데,, 껍질 까보면 개에바 진짜
> refactor: 식품 필터링 조회 API 스펙 수정

- backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> refactor: API 스펙 수정

- backend/src/main/java/zipgo/petfood/domain/StringArrayConverter.java
- backend/src/test/java/zipgo/petfood/domain/repository/PetFoodRepositoryTest.java
- backend/src/test/resources/insert-empty-functionality.sql
> hotfix: 기능성 빈문자열은 빈 리스트로 변환

- frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> NavigationBar 컴포넌트 onChangeNav props를 추가했습니다.
NavBar 부모 컴포넌트에서 state를 선언하고 setState 함수를 넣으시면 됩니다
close #122
>
> refactor: NavBar 누락된 index 바뀔 때의 이벤트 prop 추가

- backend/build.gradle
> hotfix: api 문서 서버 url 변경

- backend/src/main/java/zipgo/petfood/presentation/dto/FilterMetadataResponse.java
> refactor: 프로퍼티명 변경

- backend/src/test/java/zipgo/auth/application/AuthServiceTest.java
- backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
- backend/src/test/java/zipgo/auth/presentation/AuthControllerMockArgumentResolverTest.java
- backend/src/test/java/zipgo/auth/presentation/AuthControllerTest.java
> #60 
> 무지성으로 짰던 것 조금 수정했습니다...
> API 명세 조금 수정했습니다
> refactor: 테스트코드 개선

- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewResponse.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewsResponse.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> refactor: review 전체 조회 dto로 한번 더 포장

- frontend/src/components/@common/Header/Header.tsx
- frontend/src/pages/Login/Login.tsx
> feature: 헤더 로그인 정보 추가

- frontend/conf/conf.d/default.conf
> nignx conf 파일 변경했습니다~ close #148 
>
> fix: nginx 라우팅 되도록 설정 변경

- frontend/.env.production
- frontend/src/components/@common/Dialog/Dialog.tsx
- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/Food/FilterBottomSheet/BrandFilterList/BrandFilterList.tsx
- frontend/src/components/Food/FilterBottomSheet/FilterBottomSheet.tsx
- frontend/src/components/Food/FilterBottomSheet/FunctionalityFilterList/FunctionalityFilterList.tsx
- frontend/src/components/Food/FilterBottomSheet/MainIngredientsFilterList/MainIngredientsFilterList.tsx
- frontend/src/components/Food/FilterBottomSheet/NutritionStandardsFilterList/NutritionStandardsFilterList.tsx
- frontend/src/components/Food/FoodProfile/FoodProfile.tsx
- frontend/src/mocks/fixtures/food.ts
- frontend/src/pages/FoodDetail/FoodDetail.tsx
- frontend/src/types/food/client.ts
> refactor: 3차 데모 QA - 1

- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/Review/ReviewItem/ReviewItem.tsx
- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/hooks/query/auth.ts
> fix: 3차 데모 QA2

- frontend/src/hooks/query/auth.ts
> 
최초 로그인 시 토큰에 null 들어가는 문제 해결
>
> fix: 최초 로그인 시 토큰에 null 들어가는 문제 해결

- backend/src/main/java/zipgo/review/domain/repository/ReviewRepository.java
- backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
- backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
- backend/src/test/resources/data.sql
- close: #199 
>  N+1 문제 해결, 조만간 fetch join 관련해서 블로깅해야겠다~
> refactor: 식품에 따른 review 조회 N+1 문제 해결

- backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
- backend/src/main/java/zipgo/review/dto/request/UpdateReviewRequest.java
> 관련된 이슈 #192
comment에 255자 validation 추가했습니다. 
>
> refactor: comment validation 추가

- frontend/src/App.tsx
- frontend/src/components/@common/AxiosInterceptors/AxiosInterceptors.tsx
- frontend/src/hooks/auth.ts
- frontend/src/hooks/query/auth.ts
- frontend/src/router/Router.tsx
`AxiosInterceptors`를 통해 `App`이 실행될 때 `axios instance` 라이프 사이클에 인증 로직을 추가하였습니다
> - close #161
> feature: api 라이프 사이클에 인증 로직 추가

- frontend/Dockerfile
- frontend/conf/conf.d/default.conf
> 스토리북 배포
- default.conf 수정: 스토리북 경로 추가
- 도커 이미지에 스토리북 빌드파일 추가
- 호스트 서버에서 ngix 컨테이너로 스토리북 빌드 폴더 복사
>
> feature: 스토리북 배포 설정

- backend/deploy-dev.sh
- backend/deploy-prod.sh
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
> #206 
내부 개발 서버 포트 : 8081
내부 프로덕션 서버 포트 : 8080으로 사용 예정이며
호스트 nginx의 리버스 프록시 설정 변경을 통해 개발 서버가 8081번 포트를 사용하도록 적용할 예정
> feat: 프로덕션 환경 분리 위한 설정파일 및 스크립트 분리

- backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
- backend/src/main/java/zipgo/petfood/application/dto/FilterDto.java
- backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java
- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
- backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
- backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodsResponse.java
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
- backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
- backend/src/test/java/zipgo/petfood/domain/fixture/PetFoodFixture.java
- backend/src/test/java/zipgo/petfood/domain/repository/PetFoodQueryRepositoryTest.java
- backend/src/test/java/zipgo/petfood/infra/persist/PetFoodRepositoryImplTest.java
- close: #209 
다음과 같은 파라미터로 요청하고
- 페이징 사이즈는 첵스랑 20으로 하기로 했는데 프론트에서 주는 값만 바꾸면 되서 변경되도 상관없음.
- 페이징 no offset 원리는 해당 로직에 써놓을게요~
다음과 같이 응답
>
> feat: 식품 리스트 조회 페이징 추가

- frontend/src/apis/food.ts
- frontend/src/components/@common/PageHeader/PageHeader.tsx
- frontend/src/components/Food/FilterBottomSheet/FilterBottomSheet.tsx
- frontend/src/components/Review/ReviewForm/ReviewForm.tsx
- frontend/src/components/Review/ReviewItem/ReviewItem.tsx
- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/context/food.tsx
- frontend/src/hooks/common/useValidQueryString.ts
- frontend/src/hooks/food.ts
- frontend/src/hooks/query/auth.ts
- frontend/src/pages/Landing/Landing.tsx
- frontend/src/pages/ReviewAddition/ReviewAddition.tsx
- frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
- frontend/src/router/Router.tsx
- frontend/src/router/routes.ts
- frontend/src/types/common/routes.ts
- frontend/src/types/common/utility.ts
- frontend/src/types/food/remote.ts
- frontend/src/utils/getValidQueries.ts
`route path`를 생성하는 메서드를 담은 객체입니다
다음과 같이 사용 가능합니다
```tsx
// static path
navigate(routerPath.home())
// dynamic path
navigate(routerPath.foodDetail({ petFoodId }))
``` 
`query string`을 생성하는 함수입니다
```tsx
type QueryStringProperty = {
[key: QueryStringPropertyKey]: QueryStringPropertyValue;
};
type QueryStringPropertyKey<T extends PropertyKey = PropertyKey> = T extends symbol
? never
: T;
type QueryStringPropertyValue = number | string | number[] | string[];
generateQueryString({ query1: 1, query2: 'query2', query3: [3, 4, 5], query4: ['q1', 'q2'] })
// ?query1=1&query2=query2&query3=3,4,5&query4=q1,q2
```
`camel case`를 `snake case`로 변경해주는 유틸리티 타입입니다
```tsx
type Snake = CamelToSnake<'thisWiiBeSnake'> // type Snake = "this_wii_be_snake"
```
> - close #166
> feature: 라우팅 경로 추상화

- backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
- backend/src/main/java/zipgo/petfood/domain/repository/FunctionalityRepository.java
- backend/src/main/java/zipgo/petfood/domain/repository/PrimaryIngredientRepository.java
- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
- backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
- backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
> #151
> 안녕안녕 친구들~ 필터링 메타데이터 동적으로 조회하는 기능.. 미리 만들어 놓긴 했는데 이제야 올리네요!
> feat: 필터링 메타데이터 조회 기능

- backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
> refactor: size default 값 지정

- backend/src/main/java/zipgo/ZipgoApplication.java
- backend/src/main/java/zipgo/brand/domain/Brand.java
- backend/src/main/java/zipgo/common/config/JpaConfig.java
- backend/src/main/java/zipgo/common/entity/BaseTimeEntity.java
- backend/src/main/java/zipgo/member/domain/Member.java
- backend/src/main/java/zipgo/petfood/domain/Functionality.java
- backend/src/main/java/zipgo/petfood/domain/PetFood.java
- backend/src/main/java/zipgo/petfood/domain/PrimaryIngredient.java
- backend/src/main/java/zipgo/petfood/domain/Reviews.java
- backend/src/main/java/zipgo/review/domain/AdverseReaction.java
> refactor: 엔티티 created_at, modified_at 필드 추가

- backend/deploy-dev.sh
- backend/deploy-prod.sh
> #226 
기존 파일들은 홈 디렉토리에 있었으나
개발환경 분리하며 ~/develop ~/production 디렉토리 생성 후 이동해줌
하지만 기존 스크립트 파일에서 경로지정이 되어있지 않아 경로가 홈디렉토리로 잡혔던 상황
이에 현재 경로로 바라보도록 수정하였음
> hotfix: 배포스크립트 수정

- backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java
> fix: totalCount 곱연산 되고 있는거 수정

- backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
- backend/src/main/java/zipgo/review/application/dto/GetReviewQueryDto.java
- backend/src/main/java/zipgo/review/application/dto/GetReviewQueryRequest.java
- backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepository.java
- backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewsResponse.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/common/GlobalExceptionHandlerTest.java
- backend/src/test/java/zipgo/common/config/QueryDslTestConfig.java
- backend/src/test/java/zipgo/member/domain/fixture/MemberFixture.java
- backend/src/test/java/zipgo/review/application/ReviewsQueryServiceTest.java
- backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
- backend/src/test/java/zipgo/review/fixture/MemberFixture.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> 리뷰 페이지네이션 했어요
- closes: #217 
> 내가 나인지 콧물인지.
data.sql 때문에 고생 좀 했어여..
앞으로 data.sql에 id 포함해서 추가한다면 꼭 다음을 실행해줘야겠어여..
```
alter table 테이블 alter column 아이디 restart with 그다음수
```
오늘은 기가 빨려고 일단 제출하고 휴식.. 리뷰 반영하며 더 고칠게여
> feat: 리뷰 페이지네이션

- frontend/src/components/Review/ReviewForm/FoodInfoInReviewForm/FoodInfoInReviewForm.stories.tsx
- frontend/src/hooks/query/auth.ts
> 
로그인 토큰을 로컬스토리지에 저장하는 코드가 누락돼서 추가했어요~~
> 
스토리 파일 하나 petFoodId가 0으로 되어있어서 배포 시 에러떠서 1로 바꿔줬어용
- close #240
> fix: 로그인 인증 토큰 저장 안되는 문제 해결

- backend/build.gradle
- backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
- backend/src/main/java/zipgo/common/logging/LoggingUtils.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
> chore: 로깅 설정 및 의존성, yml 추가

- backend/src/main/resources/application.yml
> chore: port 제거

- backend/http/get-review-metadata.http
- backend/src/main/java/zipgo/pet/domain/AgeGroup.java
- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
- backend/src/main/java/zipgo/review/application/SortBy.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewMetadataResponse.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> 프론트엔드 리뷰 조회요청에 필요한 요소들을 보내줍니다.
너무 길어져서 json은 지움
>
> feat: 리뷰 메타데이터 조회 기능

- backend/build.gradle
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/error-appender.xml
- backend/src/main/resources/info-appender.xml
- backend/src/main/resources/log4jdbc-log4j2.yml
- backend/src/main/resources/logback-spring.xml
- backend/src/main/resources/warn-appender.xml
> #216 
- 에러 레벨 별로 로그 추가 및 appender 분리 작업(info, warn, error) 
- 쿼리 로그 추가
>
> chore: appender 분리 및 쿼리 로그 추가

- backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
- backend/src/main/java/zipgo/common/config/S3Config.java
- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/pet/domain/Pet.java
- backend/src/main/java/zipgo/pet/domain/repository/PetRepository.java
- backend/src/main/java/zipgo/pet/exception/PetException.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/pet/presentation/dto/request/UpdatePetRequest.java
- backend/src/test/java/zipgo/pet/application/PetServiceTest.java
- backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
>  #258 
> 반려동물 정보 수정 API 구현
코드퀄리티를 내주고 속도를 얻었습니다..
> feat: 반려동물 정보 수정 기능

- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/pet/domain/repository/BreedsRepository.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/pet/presentation/dto/response/BreedsResponses.java
- backend/src/test/java/zipgo/pet/application/PetServiceTest.java
- backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
> #262 
> 
견종 목록을 조회합니다
특이사항 : 페이징 없음
> feat: 견종 목록 조회 기능

- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/hooks/query/auth.ts
- frontend/src/mocks/fixtures/auth.ts
- frontend/src/types/auth/remote.ts
> 
> 펫을 등록하지 않았을 때 
> ➡️ 리뷰 작성 안되게 해주세요!
```JSON
{
"name": "이름",
"profileImgUrl": "사진",
"hasPet": false
}
```
>
> feat: 반려동물이 등록되지 않은 경우 리뷰 작성 못하도록 수정

- backend/src/main/java/zipgo/image/presentaion/ImageController.java
- backend/src/main/java/zipgo/pet/application/PetQueryService.java
- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/pet/domain/repository/PetRepository.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/pet/presentation/dto/response/PetResponse.java
- backend/src/main/java/zipgo/pet/presentation/dto/response/PetResponses.java
- backend/src/test/java/zipgo/image/presentaion/ImageControllerTest.java
- backend/src/test/java/zipgo/pet/application/PetQueryServiceTest.java
- backend/src/test/java/zipgo/pet/application/PetServiceTest.java
- backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
- backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
> #260 
> 로그인 정보를 통해 사용자의 반려견 목록을 조회하는 API를 구현하였음
> feature: 반려동물 목록 조회 기능

- backend/src/main/java/zipgo/image/presentaion/ImageController.java
- backend/src/main/java/zipgo/pet/application/PetQueryService.java
- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/pet/presentation/dto/request/CreatePetRequest.java
- backend/src/main/java/zipgo/pet/presentation/dto/request/UpdatePetRequest.java
- backend/src/test/java/zipgo/image/presentaion/ImageControllerTest.java
- backend/src/test/java/zipgo/pet/application/PetQueryServiceTest.java
- backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
> #261 
>  단일 반려동물의 정보를 조회하는 기능을 구현합니다
> feature: 반려동물 정보 조회 기능

- frontend/.eslintrc.js
- frontend/src/apis/review.ts
- frontend/src/components/Review/ReviewList/ReviewControls/ReviewControls.tsx
- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/components/Review/ReviewList/SummaryChart/SummaryChart.tsx
- frontend/src/constants/review.ts
- frontend/src/hooks/query/review.ts
- frontend/src/mocks/fixtures/review.ts
- frontend/src/mocks/handlers/review.ts
- frontend/src/pages/FoodDetail/FoodDetail.tsx
- frontend/src/styles/theme.ts
- frontend/src/types/common/env.d.ts
- frontend/src/types/common/global.d.ts
- frontend/src/types/common/invariantOf.d.ts
- frontend/src/types/common/utility.ts
- frontend/src/types/review/client.ts
- frontend/src/types/review/remote.ts
- frontend/src/utils/invariantOf.ts
- frontend/src/utils/review.ts
기존에 구현한 Tabs 컴포넌트를 활용하여 SummaryChart 컴포넌트를 구성하였습니다
Tabs 컴포넌트는 탭에 따른 기본 동작(탭에 맞는 패널 열기)과 접근성 속성을 지원합니다
```jsx
<Tabs defaultValue={summaryKeywords[0]} asChild>
<ChartContainer>
<Tabs.List aria-label="리뷰 요약 카테고리 탭 목록" asChild>
<NavList>
{summaryKeywords.map(keyword => (
<Tabs.Trigger key={keyword} value={keyword} asChild>
{({ selected }) => (
<NavItem $selected={selected}>{translateSummaryKeyword({ keyword })}</NavItem>
)}
</Tabs.Trigger>
))}
</NavList>
</Tabs.List>
{summaryKeywords.map(keyword => (
<Tabs.Content key={keyword} value={keyword} asChild>
<SummaryChartContentWrapper>
<QueryBoundary loadingFallback={<SummaryChartContent.Skeleton />}>
<SummaryChartContent keyword={keyword} />
</QueryBoundary>
</SummaryChartContentWrapper>
</Tabs.Content>
))}
</ChartContainer>
</Tabs>
```
브랜드 타입 …
> feat: 리뷰 요약 정보 탭 구현

- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/pet/domain/Pet.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/pet/presentation/dto/response/PetResponse.java
- backend/src/test/java/zipgo/pet/application/PetServiceTest.java
- backend/src/test/java/zipgo/pet/presentation/PetControllerTest.java
> #259 
> 
반려동물 삭제 기능 구현 및
PetResponse.petId -> PetResponse.id 변경
> feat: 반려동물 삭제 기능

- frontend/src/hooks/food.ts
> close #296
랜딩페이지에 isFetching을 쓰고있는데, 훅에서 isFetching이 없었네요.. 저장을 잘못해서 올린듯 고쳤습니다!
>
> fix: 랜딩페이지 누락된 isFetching 추가

- backend/src/main/java/zipgo/petfood/domain/PetFood.java
- backend/src/main/java/zipgo/petfood/domain/Reviews.java
- backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java
- backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepository.java
- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
- backend/src/main/java/zipgo/review/application/ReviewService.java
- backend/src/main/java/zipgo/review/domain/type/StoolCondition.java
- backend/src/main/java/zipgo/review/domain/type/TastePreference.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewSummaryResponse.java
- backend/src/main/java/zipgo/review/dto/response/GetReviewsSummaryResponse.java
- backend/src/main/java/zipgo/review/dto/response/RatingSummaryElement.java
- backend/src/main/java/zipgo/review/dto/response/SummaryElement.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
- backend/src/test/resources/application.yml
- close: #273 
뭔가 더 리팩토링 할 수 있을거 같은데 머리 과부하로 pr 날립니다~
>
> feat: 리뷰 요약 조회 기능 구현

- backend/src/main/resources/logback-spring.xml
- close: #216
이상한거 나오는거 없애고 쿼리 + 실행시간만 나오도록 수정했습니다.
>
> chore: 쿼리 로깅 수정

- frontend/.eslintrc.js
- frontend/src/assets/svg/add_pet_button.svg
- frontend/src/assets/svg/bottom_drop_icon.svg
- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/@common/Header/UserProfile.tsx
- frontend/src/components/PetProfile/GenderRadioInput.tsx
- frontend/src/components/PetProfile/PetItem.tsx
- frontend/src/components/PetProfile/PetList.tsx
- frontend/src/components/PetProfile/PetListBottomSheet.tsx
- frontend/src/context/Select/SelectContext.tsx
- frontend/src/context/petProfile/PetProfileContext.tsx
- frontend/src/hooks/auth.ts
- frontend/src/types/auth/client.ts
> close #268 
펫 프로필이랑 로그아웃 구현했습니다
근데 펫 프로필을 context로 쓰고 있는데.. 흠 
추가적으로 필요한 게 있어요.
1. 펫 정보 수정했을 때 context update
2. 리뷰 작성 버튼 존재 여부를 context? 또는 storage에 따라 다르게 줘야 합니다..
제가 펫 추가하기 버튼까지 해놨어요~
>
> feat: 펫 프로필 구현, 로그아웃 구현

- backend/deploy-dev.sh
- backend/deploy-prod.sh
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
> feat: 운영환경 분리 위한 스크립트 파일 내용 변경

- frontend/src/apis/food.ts
- frontend/src/apis/review.ts
- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/mocks/handlers/review.ts
- frontend/src/types/review/remote.ts
> feat: 리뷰 조회 응답 스키마 수정 및 정렬, 필터에 따라 재조회

- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/@common/Header/UserProfile.tsx
- frontend/src/hooks/auth.ts
> fix: 헤더 로그인 및 레이아웃 깨짐 수정

- backend/src/main/java/zipgo/image/application/ImageClient.java
- backend/src/main/java/zipgo/image/application/ImageService.java
- backend/src/main/java/zipgo/image/infrastructure/aws/s3/S3PetImageClient.java
- backend/src/main/java/zipgo/pet/application/PetService.java
- backend/src/main/java/zipgo/review/domain/repository/ReviewRepository.java
- backend/src/test/java/zipgo/image/application/ImageServiceTest.java
> #259 
>  수정시 연관된 리뷰 같이 삭제하는 로직 추가
> hotfix : 반려동물 삭제 기능 버그 수정

- backend/src/main/java/zipgo/common/config/WebConfig.java
> hotfix : 신규 배포 환경 CORS 옵션 추가

- backend/deploy-dev.sh
- backend/src/main/java/zipgo/common/config/WebConfig.java
> chore: 배포 스크립트 포트 수정

- backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepository.java
- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
>  리뷰 없을 때도 퍼센트 제대로 나오도록 로직 수정
>
> fix: 리뷰 없을 때도 퍼센트 제대로 나오도록 로직 수정

- backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepository.java
> chore: query 로깅 추가

- frontend/src/apis/review.ts
> fix: 잘못된 api 경로 수정

- backend/src/main/java/zipgo/auth/presentation/AuthInterceptor.java
>  인터셉터에서 Preflight Request 검증 로직 추가
>
> hotfix: Interceptor 내 preflight 검증 로직 추가

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
> chore: server port 8080으로 지정

- frontend/src/apis/auth.ts
- frontend/src/apis/index.ts
- frontend/src/apis/review.ts
- frontend/src/components/@common/AxiosInterceptors/AxiosInterceptors.tsx
- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/@common/Header/UserProfile.tsx
- frontend/src/components/Review/ReviewItem/ReviewItem.tsx
- frontend/src/components/Review/ReviewList/ReviewList.tsx
- frontend/src/components/Review/ReviewList/SummaryChart/SummaryChart.tsx
- frontend/src/hooks/auth.ts
- frontend/src/hooks/query/auth.ts
- frontend/src/mocks/handlers/review.ts
- frontend/src/types/auth/client.ts
- frontend/src/types/auth/remote.ts
- frontend/src/types/review/remote.ts
도움이 돼요 기능은 다시 손봐야 합니다..
> - close #327
> fix: 4차 데모 QA 반영

- frontend/src/components/Review/ReviewList/SummaryChart/SummaryChart.tsx
- frontend/src/hooks/query/auth.ts
- 로그인 후 유저 인증 쿼리를 무효화하여 로그인 정보를 최신화 하였습니다
> - close #336
> fix: 로그인 후 유저 인증 쿼리 무효화

- frontend/src/hooks/auth.ts
- 로그아웃 후 유저 인증 쿼리를 무효화하여 유저 정보 최신화
> - close #338
> fix: 로그아웃 후 유저 인증 쿼리 무효화

- backend/http/delete-helpfulreaction.http
- backend/src/main/java/zipgo/review/application/ReviewService.java
- backend/src/main/java/zipgo/review/domain/repository/HelpfulReactionRepository.java
- backend/src/test/java/zipgo/review/application/ReviewsServiceTest.java
> fix: save 호출

- frontend/src/components/PetProfile/PetListBottomSheet.tsx
- frontend/src/components/Review/ReviewItem/ReviewItem.tsx
- frontend/src/pages/Landing/Landing.tsx
- 랜딩 배너 및 인트로 드래그 방지
- 다이얼로그 로딩 스피너 노출 방식 개선(쿼리 바운더리 적용 범위 수정)
- 리뷰에 반려동물 정보 추가(종, 무게, 사이즈, 나이)
> - close #340
> feat: 4차 데모 UX 개선

- backend/src/main/java/zipgo/auth/presentation/AuthController.java
- backend/src/main/java/zipgo/auth/presentation/JwtMandatoryArgumentResolver.java
- backend/src/main/java/zipgo/auth/presentation/OptionalJwtArgumentResolver.java
- backend/src/main/java/zipgo/auth/presentation/dto/AuthCredentials.java
- backend/src/main/java/zipgo/pet/presentation/PetController.java
- backend/src/main/java/zipgo/review/presentation/ReviewController.java
- backend/src/test/java/zipgo/auth/presentation/AuthControllerMockArgumentResolverTest.java
> #283 
> 
만들땐 몰랐는데 쓸 땐 확실히 구리다는 것을 느꼈습니다
네이밍 변경했어요
> refactor: AuthDto -> AuthCredentials 네이밍 변경

- backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryImpl.java
> fix: 사용하지 않는 로그, 세미콜론 제거

- .github/workflows/frontend-deploy.yml
- frontend/Dockerfile
- frontend/Dockerfile.dev
> 
> 캐싱이 필요할 것 같은 속도긴 하지만 어쨌든... 했습니다
> chore: 프론트엔드 배포 워크플로우 작성

- frontend/public/index.html
> feat: Google Analytics 스크립트 코드 심기

- backend/src/main/java/zipgo/member/domain/Member.java
- backend/src/main/java/zipgo/pet/domain/Pet.java
- backend/src/main/java/zipgo/review/application/ReviewService.java
- backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
- backend/src/main/java/zipgo/review/exception/InvalidPetOwnerException.java
- backend/src/test/java/zipgo/member/domain/MemberTest.java
- backend/src/test/java/zipgo/petfood/domain/ReviewsTest.java
- backend/src/test/java/zipgo/review/application/ReviewsServiceTest.java
- backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
- backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> 오예~
- closes: #379 
> 굳 DB를 수정하지않아도 됩니다 ㅎㅎ
원래 이렇게 설계를 해둬서!
> feat: 유저당 반려동물이 여러마리 등록 가능

- backend/docker/docker-compose.dev.yml
- backend/src/main/java/zipgo/admin/application/AdminQueryService.java
- backend/src/main/java/zipgo/admin/application/AdminService.java
- backend/src/main/java/zipgo/admin/dto/PetFoodReadResponse.java
- backend/src/main/java/zipgo/admin/dto/PetFoodUpdateRequest.java
- backend/src/main/java/zipgo/admin/presentation/AdminController.java
- backend/src/main/java/zipgo/brand/domain/Brand.java
- backend/src/main/java/zipgo/brand/domain/repository/BrandRepository.java
- backend/src/main/java/zipgo/brand/exception/BrandNotFoundException.java
- backend/src/main/java/zipgo/petfood/domain/HasStandard.java
- backend/src/main/java/zipgo/petfood/domain/PetFood.java
- backend/src/main/java/zipgo/petfood/domain/repository/FunctionalityRepository.java
- backend/src/main/java/zipgo/petfood/domain/repository/PrimaryIngredientRepository.java
- backend/src/main/java/zipgo/petfood/exception/FunctionalityNotFoundException.java
- backend/src/main/java/zipgo/petfood/exception/PrimaryIngredientNotFoundException.java
- backend/src/main/resources/templates/admin/login.html
- backend/src/main/resources/templates/admin/pet-foods.html
- backend/src/main/resources/templates/admin/view.html
- backend/src/main/resources/templates/fragments/sidebar.html
- backend/src/test/java/zipgo/admin/application/AdminQueryServiceTest.java
- backend/src/test/java/zipgo/admin/application/AdminServiceTest.java
- backend/src/test/java/zipgo/brand/domain/BrandTest.java
- backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
- backend/src/test/java/zipgo/petfood/domain/fixture/PetFoodPrimaryIngredientFixture.java
- backend/src/test/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryTest.java
- backend/src/test/java/zipgo/petfood/presentation/PetFoodControllerTest.java
> #386 
기능성, 주원료 연관관계가 복잡해서 서비스 코드가 쪼금 많아졌네요ㅠ 이미지 파일로 넣을 수 있도록 추가하고 싶었는데, 수정할 때 삭제 -> 생성으로 할 지, 그냥 생성만 할지 정해지지가 않아서 url로 만들었습니다.
제가 생각해본건 이미지 엔티티를 분리하는거였어요! 이미지 엔티티를 분리하면 이미지도 소프트 딜리트가 가능하니까요 ㅎㅎ 여러분들의 의견이 궁금합니다
++ 다들 타임리프에 익숙하지는 않을 것 같아서 커밋 단위를 최대한 작게 가져갔습니다!
> feat: 어드민 페이지 식품 조회/수정/삭제

- backend/src/main/java/zipgo/pet/domain/repository/BreedRepository.java
- backend/src/main/java/zipgo/review/application/ReviewQueryService.java
이전
```
select * from breed where name = '';
```
이후
```
select * from breed where name like '%%';
```
앞으로 컨플릭트를 잘 해결하겠습니다🙇🏻‍♂️
> fix: 믹스견 목록 조회 쿼리문 수정

- frontend/Dockerfile.dev
> 
```tsx
// Dockerfile.dev
FROM node:18 as builder # 수정!!
WORKDIR /app
COPY . /app
RUN yarn build:dev
#RUN yarn build:sb
FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /app/dist /usr/share/nginx/html
#COPY --from=builder /app/storybook-static /usr/share/nginx/html/storybook
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
```
> fix: 도커파일 베이스이미지 수정

- frontend/src/components/Food/FoodList/FoodList.tsx
> feat: 식품 필터링 결과 없을 때 텍스트 추가

- frontend/src/pages/Landing/Landing.tsx
> fix: 이스터에그 오탈자 수정(꺠 -> 깨)

- .github/workflows/frontend-deploy-dev.yml
- .github/workflows/frontend-deploy-prod.yml
> 
Frontend Deploy to Dev, Frontend Deploy to Prod 워크플로우에 캐시를 적용했어요
> 
- close #469
> chore: 프론트엔드 프로젝트 배포 워크플로우에 캐시적용

- backend/build.gradle
- backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
- backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryImpl.java
> feat: Datadog Trace 어노테이션 추가

- backend/src/main/java/zipgo/auth/exception/TokenMissingException.java
- backend/src/main/java/zipgo/auth/support/BearerTokenExtractor.java
- backend/src/test/java/zipgo/auth/support/BearerTokenExtractorTest.java
> 토큰 API 명세 변경
토큰이 없는 경우 401에러를 반환합니다.
>
> fix: 토큰이 없는 경우 예외 변경

- backend/src/main/java/zipgo/common/config/WebConfig.java
> feat: localhost https 추가

- backend/src/main/java/zipgo/auth/dto/AuthCredentials.java
- backend/src/main/java/zipgo/auth/presentation/AuthController.java
- backend/src/main/java/zipgo/auth/presentation/JwtMandatoryArgumentResolver.java
- backend/src/main/java/zipgo/auth/presentation/OptionalJwtArgumentResolver.java
- backend/src/test/java/zipgo/auth/presentation/AuthControllerMockArgumentResolverTest.java
- backend/src/test/java/zipgo/auth/presentation/AuthControllerTest.java
> refactor: refreshToken 플로우 변경

- frontend/src/apis/auth.ts
- frontend/src/apis/index.ts
- frontend/src/components/@common/Template.tsx
- frontend/src/components/@common/Toast/Toast.tsx
- frontend/src/components/Review/ReviewForm/FoodInfoInReviewForm/FoodInfoInReviewForm.tsx
- frontend/src/components/Review/ReviewListAndChart/ReviewControls/FilterDialog/FilterDialog.tsx
- frontend/src/hooks/query/auth.ts
- frontend/src/hooks/query/review.ts
- frontend/src/hooks/review/useReviewForm.ts
- frontend/src/mocks/fixtures/auth.ts
- frontend/src/pages/FoodDetail/FoodDetail.tsx
- frontend/src/pages/Review/ReviewFormFunnel.tsx
- frontend/src/types/auth/client.ts
- frontend/src/types/auth/remote.ts
- frontend/src/types/review/remote.ts
- refresh token을 cookie > jwt로 수정
- refresh 로직 추가
- 별점 및 좋아요 기존 버그 수정(별점 비동기화, 좋아요 버벅임)
- 데스크탑 반응형 깨지는 부분 수정
> - close #502
> refactor: 리프레시 쿠키 > JWT 변경 및 버그 + 개선 사항 반영

- frontend/src/components/Food/FoodList/FoodList.tsx
- frontend/src/components/Review/ReviewListAndChart/SummaryChart/SummaryChart.tsx
- frontend/src/hooks/query/food.ts
- frontend/src/pages/FoodDetail/FoodDetail.tsx
- frontend/src/pages/Landing/Landing.tsx
> close #507 
> close #508 
> close #509 
> 툴팁, 스켈레톤 ui 렌더링, 리뷰 서머리 차트 바 width 동일하게 수정했습니다.
> fix: UI 깨짐, 스켈레톤 UI 수정

- frontend/src/components/PetProfile/PetListBottomSheet.tsx
- frontend/src/constants/time.ts
- frontend/src/hooks/petProfile/usePetProfileEdition.ts
- frontend/src/hooks/query/food.ts
- frontend/src/hooks/query/petProfile.ts
- frontend/src/hooks/query/review.ts
- 리뷰, 펫 프로필 업데이트에 따라 상태 동기화
> - close #510
> hotfix: 리뷰, 펫 프로필 업데이트에 따라 상태 동기화
